"""Add author field to channel model

Revision ID: 5e28a9b6e2a3
Revises: 3ebbf57db296
Create Date: 2023-09-20 16:57:15.120579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e28a9b6e2a3'
down_revision = '3ebbf57db296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('author', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'author')
    # ### end Alembic commands ###
